### PR TITLE
fix: allow 404 on tag list for virtual repositories

### LINKED ISSUE #527: [conformance] Allow 404 on tag list for management test
The management test of conformance test tries to list tags after deleting the last manifest, and the test expect 200 with an empty list.

https://github.com/opencontainers/distribution-spec/blob/a47ad5164a41dd04115eaad0c5a5bec49f96f9ca/conformance/04_management_test.go#L129-L140

The test makes sense if the repository is explicitly created. However, some registry providers consider that the repositories are virtual. That is, when the last manifest is deleted from the repository, the repository is considered non-existing. In that case, calling to the tag list API should return 404 since the repository is not found.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Fix #527

### CODE REVIEW

**Review by dmcgowan — DISMISSED** [review]

File: conformance/04_management_test.go [hunk 1]
```diff
@@ -131,12 +131,17 @@ var test04ContentManagement = func() {
...
+					Equal(http.StatusNotFound),
+					Equal(http.StatusOK),
+				))
+				if resp.StatusCode() == http.StatusOK {
+					tagList := &TagList{}
+					jsonData := []byte(resp.String())
+					err = json.Unmarshal(jsonData, tagList)
+					Expect(err).To(BeNil())
+					Expect(len(tagList.Tags)).To(BeNumerically("<", numTags))
+				}
```
Comment (sudo-bmitch) [inline conformance/04_management_test.go:144]: Since we are pushing and deleting a single tag, does it make sense to include a strict equal comparison?

```suggestion
				expectTags := numTags - 1
				if resp.StatusCode() == http.StatusOK {
					tagList := &TagList{}
					jsonData := []byte(resp.String())
					err = json.Unmarshal(jsonData, tagList)
					Expect(err).To(BeNil())
					Expect(len(tagList.Tags)).To(Equal(expectTags))
				}
				if resp.StatusCode() == http.StatusNotFound {
					Expect(expectTags).To(Equal(0))
				}
```

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]

File: conformance/04_management_test.go (hunk 1 above)
Comment (sajayantony) [reply conformance/04_management_test.go:144]: Could we maybe push 2 tags to avoid deletion of the repo? 
if not then as long as we accept 404 I think It’s ok.

Comment (sudo-bmitch) [reply conformance/04_management_test.go:144]: I'm okay with either, but if we added a second tag, we'd need to remove it in a later teardown.

Comment (shizhMSFT) [reply conformance/04_management_test.go]: @sudo-bmitch I've applied the requested changes.

**Review by sudo-bmitch — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM
