### PR TITLE
fix discovery teardown

### LINKED ISSUE #457: Conformance Test: `References teardown` should expect 404 response
After deleting the subject manifest, the registry can trigger cascade deletion and automatically delete the reference manifest. If the test tries to delete the reference manifest again, it should also expect 404 response.

1. Delete subject manifest
https://github.com/opencontainers/distribution-spec/blob/6bc87156eacf3b73362db343eb6b63d7abeedf7e/conformance/03_discovery_test.go#L440

2. Delete the reference manifest again
https://github.com/opencontainers/distribution-spec/blob/6bc87156eacf3b73362db343eb6b63d7abeedf7e/conformance/03_discovery_test.go#L442

### PR DESCRIPTION
**Pull request by waynr**
Discovery test teardown was broken prior to this because it would attempt to
delete a blob before deleting at least five manifests left over from the setup
that still reference it. Most registries probably don't care about deleting
content that's referenced by other content, which is probably why this works
for others.

Also, I was seeing `GET /v2/<name>/tags/list?n=0` requests and then out of
bounds indexing into the resulting slice because of the weird logic used to
calculate what the `n` parameter should be in the tag listing endpoint tests.

Fixes #457.

### CODE REVIEW

**Comment by mikebrow** [comment]
pls sign commits

File: conformance/03_discovery_test.go [hunk 1]
```diff
@@ -351,16 +352,29 @@ var test03ContentDiscovery = func() {
...
-					Expect(resp.StatusCode()).To(SatisfyAny(
-						SatisfyAll(
-							BeNumerically(">=", 200),
-							BeNumerically("<", 300),
-						),
-						Equal(http.StatusMethodNotAllowed),
-					))
+					references := []string{
+						refsIndexArtifactDigest,
+						manifests[2].Digest,
```
Comment (sudo-bmitch) [inline conformance/03_discovery_test.go:357]: Add `manifests[4]`:

```suggestion
						manifests[2].Digest,
						manifests[4].Digest,
```

File: conformance/03_discovery_test.go [hunk 2]
```diff
@@ -398,16 +412,29 @@ var test03ContentDiscovery = func() {
...
```
Comment (sudo-bmitch) [inline conformance/03_discovery_test.go:417]:
```suggestion
						manifests[2].Digest,
						manifests[4].Digest,
```

File: conformance/03_discovery_test.go [hunk 3]
```diff
@@ -398,16 +412,29 @@ var test03ContentDiscovery = func() {
...
+						refsManifestAConfigArtifactDigest,
+						refsManifestAConfigArtifactDigest,
```
Comment (sudo-bmitch) [inline conformance/03_discovery_test.go:419]:
```suggestion
```

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
Couple minor changes to align all the manifests.

**Comment by sudo-bmitch** [comment]
@waynr do you have time to work on the changes requested? If not, I can take a stab at it.

**Comment by waynr** [comment]
@sudo-bmitch I accepted your suggested changes, thanks for the reminder!

**Review by jdolitsky — APPROVED** [review]
